### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Roboe** [NacionLumpen/nacionlumpen.github.io#5]
> Today, custom domains on GitHub Pages are gaining support for HTTPS as well, meaning over a million GitHub Pages sites will be served over HTTPS.
> 
> HTTPS (most recognizable as the lock icon in your browser’s address bar) encrypts traffic between GitHub’s servers and your browser giving you confidence that the page you asked for is the page you’re reading, from the site you think it is, and that others can’t snoop on or modify its contents along the way.
> [&hellip;]
> We have partnered with the certificate authority Let’s Encrypt on this project.

Source & howto: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by sortega** [comment]
Definitively will do this

**Comment by sortega** [comment]
HTTPS is working for me (with redirection from http to https)
Closing

**Comment by Roboe** [comment]
Great! Well done, 🙌
